//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellarTrackerAddIn2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CellarTrackerAddIn2.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static byte[] CellarContents {
            get {
                object obj = ResourceManager.GetObject("CellarContents", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] CellarData {
            get {
                object obj = ResourceManager.GetObject("CellarData", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] CellarDrinkability {
            get {
                object obj = ResourceManager.GetObject("CellarDrinkability", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] CellarDrinkWine {
            get {
                object obj = ResourceManager.GetObject("CellarDrinkWine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] CellarMain {
            get {
                object obj = ResourceManager.GetObject("CellarMain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] CellarNotesFromOthers {
            get {
                object obj = ResourceManager.GetObject("CellarNotesFromOthers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] CellarSettings {
            get {
                object obj = ResourceManager.GetObject("CellarSettings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] CellarWineDetail {
            get {
                object obj = ResourceManager.GetObject("CellarWineDetail", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Controls {
            get {
                object obj = ResourceManager.GetObject("Controls", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Controls1 {
            get {
                object obj = ResourceManager.GetObject("Controls1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] Default {
            get {
                object obj = ResourceManager.GetObject("Default", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static System.Drawing.Bitmap WineBarrel {
            get {
                object obj = ResourceManager.GetObject("WineBarrel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
